#!/usr/bin/env python3
"""
GX53 –í—Å—Ç—Ä–∞–∏–≤–∞–µ–º—ã–π —Å–≤–µ—Ç–∏–ª—å–Ω–∏–∫ OGX-R1-001-GX53-DIY
3D –º–æ–¥–µ–ª—å –¥–ª—è –≤–∏–∑—É–∞–ª–∏–∑–∞—Ü–∏–∏
–†–∞–∑–º–µ—Ä—ã –ø–æ —Ñ–æ—Ç–æ –æ—Ç –ú–∏—Ö–∞–∏–ª–∞ (–≠–≤–µ—Ä–µ—Å—Ç-–¢–µ—Ö)
"""

import sys
sys.path.append('/Applications/FreeCAD.app/Contents/Resources/lib')

import FreeCAD
import Part
import math

# === –†–ê–ó–ú–ï–†–´ (–º–º) ===
OUTER_DIAMETER = 106.0      # –í–Ω–µ—à–Ω–∏–π –¥–∏–∞–º–µ—Ç—Ä
CUTOUT_DIAMETER = 90.0      # –í—Ä–µ–∑–Ω–æ–µ –æ—Ç–≤–µ—Ä—Å—Ç–∏–µ  
INNER_DIAMETER = 53.0       # –ü–æ—Å–∞–¥–∫–∞ –ø–æ–¥ GX53
TOTAL_HEIGHT = 23.0         # –û–±—â–∞—è –≤—ã—Å–æ—Ç–∞
FLANGE_HEIGHT = 4.0         # –í—ã—Å–æ—Ç–∞ —Ñ–ª–∞–Ω—Ü–∞ (–≤–∏–¥–∏–º–∞—è —á–∞—Å—Ç—å)
BODY_HEIGHT = 19.0          # –í—ã—Å–æ—Ç–∞ –∫–æ—Ä–ø—É—Å–∞ (–≤ –ø–æ—Ç–æ–ª–∫–µ)
WALL_THICKNESS = 1.5        # –¢–æ–ª—â–∏–Ω–∞ —Å—Ç–µ–Ω–∫–∏

# –ü—Ä—É–∂–∏–Ω—ã
SPRING_WIRE_DIA = 1.5       # –î–∏–∞–º–µ—Ç—Ä –ø—Ä–æ–≤–æ–ª–æ–∫–∏
SPRING_WIDTH = 25.0         # –®–∏—Ä–∏–Ω–∞ –ø—Ä—É–∂–∏–Ω—ã
SPRING_LENGTH = 35.0        # –î–ª–∏–Ω–∞ –ø—Ä—É–∂–∏–Ω—ã

def create_lamp_body():
    """–°–æ–∑–¥–∞—ë—Ç –∫–æ—Ä–ø—É—Å —Å–≤–µ—Ç–∏–ª—å–Ω–∏–∫–∞"""
    doc = FreeCAD.newDocument("GX53_Lamp")
    
    # === –§–õ–ê–ù–ï–¶ (–≤–∏–¥–∏–º–∞—è —á–∞—Å—Ç—å) ===
    # –í–Ω–µ—à–Ω–µ–µ –∫–æ–ª—å—Ü–æ —Ñ–ª–∞–Ω—Ü–∞
    flange_outer = Part.makeCylinder(
        OUTER_DIAMETER / 2,  # —Ä–∞–¥–∏—É—Å
        FLANGE_HEIGHT,       # –≤—ã—Å–æ—Ç–∞
        FreeCAD.Vector(0, 0, BODY_HEIGHT)  # –ø–æ–∑–∏—Ü–∏—è (—Å–≤–µ—Ä—Ö—É)
    )
    
    # –í—ã—Ä–µ–∑ –ø–æ–¥ –ª–∞–º–ø—É (—Ü–µ–Ω—Ç—Ä–∞–ª—å–Ω–æ–µ –æ—Ç–≤–µ—Ä—Å—Ç–∏–µ)
    flange_hole = Part.makeCylinder(
        INNER_DIAMETER / 2,
        FLANGE_HEIGHT + 1,
        FreeCAD.Vector(0, 0, BODY_HEIGHT - 0.5)
    )
    
    flange = flange_outer.cut(flange_hole)
    
    # === –ö–û–†–ü–£–° (–≤ –ø–æ—Ç–æ–ª–∫–µ) ===
    # –í–Ω–µ—à–Ω—è—è —Å—Ç–µ–Ω–∫–∞ –∫–æ—Ä–ø—É—Å–∞
    body_outer = Part.makeCylinder(
        CUTOUT_DIAMETER / 2 - 1,  # —á—É—Ç—å –º–µ–Ω—å—à–µ –≤—Ä–µ–∑–Ω–æ–≥–æ –æ—Ç–≤–µ—Ä—Å—Ç–∏—è
        BODY_HEIGHT,
        FreeCAD.Vector(0, 0, 0)
    )
    
    # –í–Ω—É—Ç—Ä–µ–Ω–Ω—è—è –ø–æ–ª–æ—Å—Ç—å
    body_inner = Part.makeCylinder(
        CUTOUT_DIAMETER / 2 - 1 - WALL_THICKNESS,
        BODY_HEIGHT - WALL_THICKNESS,
        FreeCAD.Vector(0, 0, WALL_THICKNESS)
    )
    
    body = body_outer.cut(body_inner)
    
    # –¶–µ–Ω—Ç—Ä–∞–ª—å–Ω–æ–µ –æ—Ç–≤–µ—Ä—Å—Ç–∏–µ —á–µ—Ä–µ–∑ –≤–µ—Å—å –∫–æ—Ä–ø—É—Å
    center_hole = Part.makeCylinder(
        INNER_DIAMETER / 2,
        TOTAL_HEIGHT + 1,
        FreeCAD.Vector(0, 0, -0.5)
    )
    
    body = body.cut(center_hole)
    
    # === –û–ë–™–ï–î–ò–ù–ï–ù–ò–ï ===
    lamp = flange.fuse(body)
    
    # === –ü–†–£–ñ–ò–ù–ù–´–ï –§–ò–ö–°–ê–¢–û–†–´ ===
    springs = []
    for angle in [0, 180]:  # –¥–≤–µ –ø—Ä—É–∂–∏–Ω—ã –Ω–∞–ø—Ä–æ—Ç–∏–≤ –¥—Ä—É–≥ –¥—Ä—É–≥–∞
        rad = math.radians(angle)
        
        # –ë–∞–∑–æ–≤–∞—è —Ç–æ—á–∫–∞ –∫—Ä–µ–ø–ª–µ–Ω–∏—è
        base_x = (CUTOUT_DIAMETER / 2 - 5) * math.cos(rad)
        base_y = (CUTOUT_DIAMETER / 2 - 5) * math.sin(rad)
        
        # –°–æ–∑–¥–∞—ë–º —É–ø—Ä–æ—â—ë–Ω–Ω—É—é –ø—Ä—É–∂–∏–Ω—É (–ø—Ä—è–º–æ—É–≥–æ–ª—å–Ω–∏–∫)
        spring_profile = Part.makeBox(
            SPRING_WIDTH,
            SPRING_WIRE_DIA * 2,
            SPRING_LENGTH,
            FreeCAD.Vector(
                base_x - SPRING_WIDTH / 2,
                base_y - SPRING_WIRE_DIA,
                5
            )
        )
        springs.append(spring_profile)
    
    # –î–æ–±–∞–≤–ª—è–µ–º –ø—Ä—É–∂–∏–Ω—ã
    for spring in springs:
        lamp = lamp.fuse(spring)
    
    # === –°–û–•–†–ê–ù–ï–ù–ò–ï ===
    # –î–æ–±–∞–≤–ª—è–µ–º –≤ –¥–æ–∫—É–º–µ–Ω—Ç
    part_obj = doc.addObject("Part::Feature", "GX53_Lamp")
    part_obj.Shape = lamp
    
    # –≠–∫—Å–ø–æ—Ä—Ç –≤ —Ä–∞–∑–Ω—ã–µ —Ñ–æ—Ä–º–∞—Ç—ã
    output_dir = "/Users/bond/.openclaw/workspace/everest-models/gx53-lamp"
    
    # STL –¥–ª—è –≤–∏–∑—É–∞–ª–∏–∑–∞—Ü–∏–∏
    lamp.exportStl(f"{output_dir}/GX53-lamp-visual.stl")
    print(f"‚úÖ STL —Å–æ—Ö—Ä–∞–Ω—ë–Ω: {output_dir}/GX53-lamp-visual.stl")
    
    # STEP –¥–ª—è –ø—Ä–æ–∏–∑–≤–æ–¥—Å—Ç–≤–∞
    lamp.exportStep(f"{output_dir}/GX53-lamp.step")
    print(f"‚úÖ STEP —Å–æ—Ö—Ä–∞–Ω—ë–Ω: {output_dir}/GX53-lamp.step")
    
    # –°–æ—Ö—Ä–∞–Ω—è–µ–º FreeCAD –¥–æ–∫—É–º–µ–Ω—Ç
    doc.saveAs(f"{output_dir}/GX53-lamp.FCStd")
    print(f"‚úÖ FreeCAD –ø—Ä–æ–µ–∫—Ç: {output_dir}/GX53-lamp.FCStd")
    
    return lamp

if __name__ == "__main__":
    print("üîß –°–æ–∑–¥–∞—é 3D –º–æ–¥–µ–ª—å —Å–≤–µ—Ç–∏–ª—å–Ω–∏–∫–∞ GX53...")
    print(f"   –í–Ω–µ—à–Ω–∏–π √ò: {OUTER_DIAMETER} –º–º")
    print(f"   –í—Ä–µ–∑–Ω–æ–µ √ò: {CUTOUT_DIAMETER} –º–º")
    print(f"   –í—ã—Å–æ—Ç–∞: {TOTAL_HEIGHT} –º–º")
    print()
    
    create_lamp_body()
    
    print()
    print("üéâ –ì–æ—Ç–æ–≤–æ!")
